name: Update Participants List

on:
  schedule:
    # Exécution à midi et minuit UTC (ajuste selon ton fuseau horaire si nécessaire)
    - cron: '0 0,12 * * *'
  workflow_dispatch:  # Permet également de lancer manuellement le workflow

jobs:
  update-participants:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Donne les permissions d'écriture au repository
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub python-dateutil
          
      - name: Update participants list
        env:
          # Utiliser github.token (token intégré de GitHub Actions)
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python .github/scripts/update_participants.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Vérifier s'il y a des modifications
          if [[ $(git status --porcelain PARTICIPANTS.md) ]]; then
            git add PARTICIPANTS.md
            current_date=$(date +"%d/%m/%Y à %H:%M")
            git commit -m "🤖 Mise à jour automatique de la liste des participants - $current_date"
            git push
          else
            echo "Aucune modification à apporter à PARTICIPANTS.md"
          fi